# Generated by Django 4.0.4 on 2022-05-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.TextField(choices=[('Category1', 'Category1'), ('Category2', 'Category2'), ('Category3', 'Category3'), ('Category4', 'Category4')]),
        ),
    ]
