# Generated by Django 4.0.4 on 2022-05-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_remove_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.TextField(choices=[('To do', 'Status1'), ('In progress', 'Status2'), ('Done', 'Status3')], default='To do'),
        ),
    ]
