# Generated by Django 4.0.4 on 2022-05-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.TextField(choices=[('To do', 'Status1'), ('In progress', 'Status2'), ('Done', 'Status3')]),
        ),
    ]
